[package]
name = "ayaka-latex"
version = "0.1.0"
edition = "2021"

[dependencies]
ayaka-runtime = { path = "../../utils/ayaka-runtime" }
tokio = { version = "1", features = ["fs", "io-util", "macros", "rt"] }
clap = { version = "4.0", features = ["derive"] }
env_logger = "0.9"
